global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "prometheus-alerts.yml"

scrape_configs:
  - job_name: 'aws-nodes'
    scrape_interval: 15s
    static_configs:
      - targets:
          - 'host.docker.internal:9101'  # manage-node-1 via SSH tunnel
          - 'host.docker.internal:9102'  # manage-node-2 via SSH tunnel
          - 'host.docker.internal:9103'  # manage-node-3 via SSH tunnel
    relabel_configs:
      - source_labels: [__address__]
        target_label: node_name
        replacement: 'manage-node-1 (Amazon Linux)'
        regex: 'host\\.docker\\.internal:9101'
      - source_labels: [__address__]
        target_label: node_name
        replacement: 'manage-node-2 (Ubuntu)'
        regex: 'host\\.docker\\.internal:9102'
      - source_labels: [__address__]
        target_label: node_name
        replacement: 'manage-node-3 (Ubuntu)'
        regex: 'host\\.docker\\.internal:9103'

  - job_name: 'fim-agents'
    scrape_interval: 30s
    static_configs:
      - targets:
          - 'host.docker.internal:8080'  # FIM agent on manage-node-1
          - 'host.docker.internal:8082'  # FIM agent on manage-node-2
          - 'host.docker.internal:8084'  # FIM agent on manage-node-3
    relabel_configs:
      - source_labels: [__address__]
        target_label: node_name
        replacement: 'manage-node-1 (Amazon Linux)'
        regex: 'host\\.docker\\.internal:8080'
      - source_labels: [__address__]
        target_label: node_name
        replacement: 'manage-node-2 (Ubuntu)'
        regex: 'host\\.docker\\.internal:8082'
      - source_labels: [__address__]
        target_label: node_name
        replacement: 'manage-node-3 (Ubuntu)'
        regex: 'host\\.docker\\.internal:8084'

  - job_name: 'cmdb-collectors'
    scrape_interval: 60s
    static_configs:
      - targets:
          - 'host.docker.internal:8081'  # CMDB collector on manage-node-1
          - 'host.docker.internal:8083'  # CMDB collector on manage-node-2
          - 'host.docker.internal:8085'  # CMDB collector on manage-node-3
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: node_name
        replacement: 'manage-node-1 (Amazon Linux)'
        regex: 'host\\.docker\\.internal:8081'
      - source_labels: [__address__]
        target_label: node_name
        replacement: 'manage-node-2 (Ubuntu)'
        regex: 'host\\.docker\\.internal:8083'
      - source_labels: [__address__]
        target_label: node_name
        replacement: 'manage-node-3 (Ubuntu)'
        regex: 'host\\.docker\\.internal:8085'
