groups:
- name: fim-alerts
  rules:
  - alert: FIMFileChange
    expr: increase(fim_events_total[5m]) > 0
    for: 0m
    labels:
      severity: warning
      service: fim
    annotations:
      summary: "File integrity monitoring detected changes"
      description: "FIM agent detected {{ $value }} file changes in the last 5 minutes on {{ $labels.instance }}"
      runbook_url: "http://localhost:8088/DRIFT-DETECTION-TESTING-GUIDE.md"

  - alert: FIMHighActivity
    expr: increase(fim_events_total[10m]) > 50
    for: 2m
    labels:
      severity: critical
      service: fim
    annotations:
      summary: "High FIM activity detected"
      description: "FIM agent detected {{ $value }} file changes in the last 10 minutes on {{ $labels.instance }} - possible security incident"
      runbook_url: "http://localhost:8088/DRIFT-DETECTION-TESTING-GUIDE.md"

  - alert: FIMAgentDown
    expr: up{job="fim-agents"} == 0
    for: 1m
    labels:
      severity: critical
      service: fim
    annotations:
      summary: "FIM agent is down"
      description: "FIM agent on {{ $labels.instance }} has been down for more than 1 minute"
      runbook_url: "http://localhost:8088/DRIFT-DETECTION-TESTING-GUIDE.md"

- name: cmdb-alerts
  rules:
  - alert: CMDBCollectionFailure
    expr: increase(cmdb_collections_total[15m]) == 0
    for: 5m
    labels:
      severity: warning
      service: cmdb
    annotations:
      summary: "CMDB collection failure"
      description: "CMDB collector on {{ $labels.instance }} has not collected data in the last 15 minutes"
      runbook_url: "http://localhost:8088/DRIFT-DETECTION-TESTING-GUIDE.md"

  - alert: CMDBCollectorDown
    expr: up{job="cmdb-collectors"} == 0
    for: 1m
    labels:
      severity: critical
      service: cmdb
    annotations:
      summary: "CMDB collector is down"
      description: "CMDB collector on {{ $labels.instance }} has been down for more than 1 minute"
      runbook_url: "http://localhost:8088/DRIFT-DETECTION-TESTING-GUIDE.md"

- name: system-alerts
  rules:
  - alert: NodeExporterDown
    expr: up{job="aws-nodes"} == 0
    for: 1m
    labels:
      severity: critical
      service: node-exporter
    annotations:
      summary: "Node Exporter is down"
      description: "Node Exporter on {{ $labels.instance }} has been down for more than 1 minute"
      runbook_url: "http://localhost:8088/DRIFT-DETECTION-TESTING-GUIDE.md"

  - alert: HighCPUUsage
    expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
    for: 5m
    labels:
      severity: warning
      service: system
    annotations:
      summary: "High CPU usage detected"
      description: "CPU usage is above 80% for more than 5 minutes on {{ $labels.instance }}"
      runbook_url: "http://localhost:8088/DRIFT-DETECTION-TESTING-GUIDE.md"

  - alert: HighMemoryUsage
    expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
    for: 5m
    labels:
      severity: warning
      service: system
    annotations:
      summary: "High memory usage detected"
      description: "Memory usage is above 85% for more than 5 minutes on {{ $labels.instance }}"
      runbook_url: "http://localhost:8088/DRIFT-DETECTION-TESTING-GUIDE.md"

  - alert: DiskSpaceLow
    expr: (1 - (node_filesystem_avail_bytes / node_filesystem_size_bytes)) * 100 > 90
    for: 5m
    labels:
      severity: critical
      service: system
    annotations:
      summary: "Disk space low"
      description: "Disk usage is above 90% for more than 5 minutes on {{ $labels.instance }}"
      runbook_url: "http://localhost:8088/DRIFT-DETECTION-TESTING-GUIDE.md"

- name: prometheus-alerts
  rules:
  - alert: PrometheusDown
    expr: up{job="prometheus"} == 0
    for: 1m
    labels:
      severity: critical
      service: prometheus
    annotations:
      summary: "Prometheus is down"
      description: "Prometheus monitoring system is down"
      runbook_url: "http://localhost:8088/DRIFT-DETECTION-TESTING-GUIDE.md"

  - alert: PrometheusConfigReloadFailed
    expr: prometheus_config_last_reload_successful == 0
    for: 0m
    labels:
      severity: warning
      service: prometheus
    annotations:
      summary: "Prometheus configuration reload failed"
      description: "Prometheus configuration reload failed"
      runbook_url: "http://localhost:8088/DRIFT-DETECTION-TESTING-GUIDE.md"