global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "prometheus-alerts.yml"

scrape_configs:
  - job_name: 'aws-nodes'
    scrape_interval: 15s
    static_configs:
      - targets:
          - 'host.docker.internal:9101'  # manage-node-1 via SSH tunnel
          - 'host.docker.internal:9102'  # manage-node-2 via SSH tunnel
          - 'host.docker.internal:9103'  # manage-node-3 via SSH tunnel

  - job_name: 'fim-agents'
    scrape_interval: 30s
    static_configs:
      - targets:
          - 'host.docker.internal:8080'  # FIM agent on manage-node-1
          - 'host.docker.internal:8082'  # FIM agent on manage-node-2
          - 'host.docker.internal:8084'  # FIM agent on manage-node-3

  - job_name: 'cmdb-collectors'
    scrape_interval: 60s
    static_configs:
      - targets:
          - 'host.docker.internal:8081'  # CMDB collector on manage-node-1
          - 'host.docker.internal:8083'  # CMDB collector on manage-node-2
          - 'host.docker.internal:8085'  # CMDB collector on manage-node-3
    metrics_path: /metrics
