global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'aws-nodes'
    scrape_interval: 15s
    static_configs:
      - targets:
          - 'host.docker.internal:9101'  # manage-node-1 via SSH tunnel
          - 'host.docker.internal:9102'  # manage-node-2 via SSH tunnel
          - 'host.docker.internal:9103'  # manage-node-3 via SSH tunnel
    metrics_path: /metrics

  - job_name: 'fim-agents'
    scrape_interval: 15s
    static_configs:
      - targets:
          - 'host.docker.internal:8080'  # manage-node-1 FIM agent
          - 'host.docker.internal:8082'  # manage-node-2 FIM agent
          - 'host.docker.internal:8084'  # manage-node-3 FIM agent
    metrics_path: /metrics

  - job_name: 'cmdb-collectors'
    scrape_interval: 15s
    static_configs:
      - targets:
          - 'host.docker.internal:8081'  # manage-node-1 CMDB collector
          - 'host.docker.internal:8083'  # manage-node-2 CMDB collector
          - 'host.docker.internal:8085'  # manage-node-3 CMDB collector
    metrics_path: /metrics
