---
# Monitoring setup tasks

- name: "Install monitoring tools"
  package:
    name: "{{ item }}"
    state: present
  loop:
    - htop
    - iotop
    - nethogs
    - sysstat

- name: "Create node_exporter user"
  user:
    name: "node_exporter"
    system: yes
    shell: /usr/sbin/nologin
    home: /var/lib/node_exporter
    create_home: no
    state: present

- name: "Create node_exporter group"
  group:
    name: "node_exporter"
    state: present

- name: "Download Node Exporter (Amazon Linux)"
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz"
    dest: "/tmp/node_exporter-1.7.0.linux-amd64.tar.gz"
    mode: '0644'
  when: ansible_distribution == "Amazon"

- name: "Download Node Exporter (Ubuntu)"
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz"
    dest: "/tmp/node_exporter-1.7.0.linux-amd64.tar.gz"
    mode: '0644'
  when: ansible_distribution == "Ubuntu"

- name: "Extract Node Exporter"
  unarchive:
    src: "/tmp/node_exporter-1.7.0.linux-amd64.tar.gz"
    dest: "/tmp/"
    remote_src: yes

- name: "Copy Node Exporter binary"
  copy:
    src: "/tmp/node_exporter-1.7.0.linux-amd64/node_exporter"
    dest: "/usr/local/bin/node_exporter"
    owner: "node_exporter"
    group: "node_exporter"
    mode: '0755'
    remote_src: yes

- name: "Create Node Exporter systemd service"
  copy:
    content: |
      [Unit]
      Description=Prometheus Node Exporter
      Wants=network-online.target
      After=network-online.target

      [Service]
      User=node_exporter
      Group=node_exporter
      Type=simple
      ExecStart=/usr/local/bin/node_exporter --web.listen-address=:9100
      Restart=always
      RestartSec=3

      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/node_exporter.service
    mode: '0644'

- name: "Reload systemd daemon"
  systemd:
    daemon_reload: yes

- name: "Enable Node Exporter service"
  systemd:
    name: node_exporter
    enabled: yes
    state: started

- name: "Configure system monitoring"
  template:
    src: monitoring.conf.j2
    dest: /etc/monitoring.conf
    mode: '0644'

- name: "Enable monitoring services"
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - sysstat
    - node_exporter

- name: "Clean up temporary files"
  file:
    path: "/tmp/node_exporter-1.7.0.linux-amd64.tar.gz"
    state: absent

- name: "Clean up extracted directory"
  file:
    path: "/tmp/node_exporter-1.7.0.linux-amd64"
    state: absent
