---
# Localhost setup playbook for macOS development
# This playbook sets up the lab environment on the local macOS machine

- name: "Local Lab Environment Setup"
  hosts: localhost
  connection: local
  gather_facts: yes
  
  vars:
    playbook_start_time: "{{ ansible_date_time.iso8601 }}"
  
  pre_tasks:
    - name: "Display setup information"
      debug:
        msg:
          - "Setting up lab environment on {{ inventory_hostname }}"
          - "Environment: {{ environment | default('development') }}"
          - "OS: {{ ansible_distribution }} {{ ansible_distribution_version }}"
          - "Playbook started at: {{ playbook_start_time }}"
  
  tasks:
    - name: "Create lab directories"
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /var/lib/fim
        - /var/lib/cmdb/data
        - /var/log/fim
        - /var/log/cmdb
        - /etc/fim
    
    - name: "Install Python dependencies"
      pip:
        name:
          - psutil
          - watchdog
          - pyyaml
          - jinja2
        state: present
        executable: "{{ ansible_python_interpreter }}"
    
    - name: "Copy FIM configuration"
      copy:
        src: "{{ playbook_dir }}/../fim/agents/fim-config.json"
        dest: /etc/fim/fim-config.json
        mode: '0644'
    
    - name: "Copy FIM agent script"
      copy:
        src: "{{ playbook_dir }}/../fim/agents/fim-agent.py"
        dest: /usr/local/bin/fim-agent.py
        mode: '0755'
    
    - name: "Copy CMDB collector script"
      copy:
        src: "{{ playbook_dir }}/../cmdb/scripts/cmdb-collector.py"
        dest: /usr/local/bin/cmdb-collector.py
        mode: '0755'
    
    - name: "Create system information file"
      copy:
        content: |
          # System Information
          # Generated by Ansible on {{ ansible_date_time.iso8601 }}
          
          Hostname: {{ ansible_hostname }}
          OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
          Architecture: {{ ansible_architecture }}
          Python: {{ ansible_python_version }}
          
          # Lab Configuration
          Environment: {{ environment | default('development') }}
          Setup Date: {{ playbook_start_time }}
          
          # Lab Components
          FIM Enabled: {{ fim_enabled | default('true') }}
          CMDB Enabled: {{ cmdb_enabled | default('true') }}
        dest: /etc/system-info
        mode: '0644'
    
    - name: "Test FIM agent"
      command: "{{ ansible_python_interpreter }} /usr/local/bin/fim-agent.py --help"
      register: fim_test
      changed_when: false
    
    - name: "Test CMDB collector"
      command: "{{ ansible_python_interpreter }} /usr/local/bin/cmdb-collector.py --help"
      register: cmdb_test
      changed_when: false
    
    - name: "Display test results"
      debug:
        msg:
          - "FIM agent test: {{ 'PASSED' if fim_test.rc == 0 else 'FAILED' }}"
          - "CMDB collector test: {{ 'PASSED' if cmdb_test.rc == 0 else 'FAILED' }}"
  
  post_tasks:
    - name: "Create setup completion marker"
      file:
        path: /etc/lab-setup-completed
        state: touch
        mode: '0644'
    
    - name: "Display completion information"
      debug:
        msg:
          - "Lab setup completed for {{ inventory_hostname }}"
          - "Setup completed at: {{ ansible_date_time.iso8601 }}"
          - "Next steps:"
          - "1. Test FIM: python3 /usr/local/bin/fim-agent.py --scan-once"
          - "2. Test CMDB: python3 /usr/local/bin/cmdb-collector.py"
          - "3. Run tests: cd tests && ./run-all-tests.sh"
